//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 11/29/2023 11:09:59 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace DBFeederEntity
{
    public partial class TableB : BaseEntity {

        public TableB()
        {
            OnCreated();
        }

        public string TITLE { get; set; }

        public string PLOT { get; set; }

        public string DIRECTOR { get; set; }

        public string WRITERS { get; set; }

        public string STARS { get; set; }

        public string MISC { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        public override bool Equals(object obj)
        {
          TableB toCompare = obj as TableB;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.TITLE, toCompare.TITLE))
            return false;

          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + TITLE.GetHashCode();
          return hashCode;
        }

        #endregion
    }

}
