//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 9/16/2023 8:17:24 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace DBFeederEntity
{
    public partial class TableA : BaseEntity {

        public TableA()
        {
            OnCreated();
        }

        public string WORD_TYPE { get; set; }

        public string WORD_VALUE { get; set; }

        public string SOURCE { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
